In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv(r"C:\Users\MR.INDIA\Desktop\Machine Learning\DataSets\townprice.csv")
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [3]:
from sklearn.preprocessing import LabelEncoder
# label = LabelEncoder()
# la = label.fit_transform(df.town)
# la

In [4]:
dummies= pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [5]:
df_dummies= pd.concat([df,dummies],axis=1)
df_dummies

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [6]:
y=df_dummies.price # price this is target variable
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [7]:
x = df_dummies.drop(['town','price'],axis=1)  # here we can use "inplace=True" because no need a new varible 
# if we can drop multiple column using ".drop['first column name','second column name']", single ".drop('column name')"
x

area  monroe township  robinsville  west windsor
0   2600                1            0             0
1   3000                1            0             0
2   3200                1            0             0
3   3600                1            0             0
4   4000                1            0             0
5   2600                0            0             1
6   2800                0            0             1
7   3300                0            0             1
8   3600                0            0             1
9   2600                0            1             0
10  2900                0            1             0
11  3100                0            1             0
12  3600                0            1             0

In [8]:
model=LinearRegression()
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
model.coef_

array([   126.89744141, -21900.12900452,   3786.28251989,  18113.84648463])

In [10]:
model.intercept_

231676.52117832535

In [11]:
model.predict([[3400,0,0,1]])

array([681241.66845839])

In [12]:
model.predict([[3800,0,1,0]])

array([717673.08105782])

In [13]:
model.predict([[4200,1,0,0]])

array([742745.64609759])

# Using LabelEncoder

In [14]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
label.fit_transform(df.town)

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1])

In [16]:
df.town=label.fit_transform(df.town)

In [17]:
df1=df
df1.head()

town  area   price
0     0  2600  550000
1     0  3000  565000
2     0  3200  610000
3     0  3600  680000
4     0  4000  725000

In [18]:
df1.shape

(13, 3)

In [19]:
real_x = df1.iloc[:,0:2].values
real_y = df1.iloc[:,2].values
# real_x = re_x.reshape(-1,1)
# real_y = re_y.reshape(-1,1)

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(real_x,real_y, test_size = 0.2,random_state =0)

In [25]:
MLR = LinearRegression()
MLR.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [26]:
yp = MLR.predict(x_test)

In [27]:
yp

array([606750.90909091, 623989.09090909, 715485.45454545])

In [28]:
y_test

array([615000, 620000, 725000], dtype=int64)